spring:
  application:
    name: spring-cqrs
  datasource:
        url: jdbc:postgresql://localhost:5432/eticaret
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
  jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
security:
  jwt:
    secret: a+mn3JdYxP2wsBITgnpIOA9zEag8EUPE022WDSwDcpPzvgdWGXb6hbskhyKK6wY1
    expirationInSeconds: 360000
    issuer: spring-cqrs