spring.application.name=library-cqrs

spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

security.jwt.secret=ChangeThisSecretKeyForDemoLibraryCqrsMustBeLongEnough1234
security.jwt.expiration-in-seconds=3600
security.jwt.issuer=library-cqrs
performance.threshold-ms=500
